---
collections:
  - name: openstack.cloud
    version: 2.1.0
  - name: https://github.com/stackhpc/ansible-collection-openstack.git
    type: git
    version: cloudkitty
  # - name: stackhpc.openstack
  #   version: 0.1.1
