---
###############################################################################
# Configuration of OpenStack projects and users user environment.

# List of OpenStack domains. Format is as required by the stackhpc.os-projects
# role.
#openstack_domains:

# List of OpenStack projects. Format is as required by the stackhpc.os-projects
# role.
#openstack_projects:

# List of OpenStack projects. Format is as required by the stackhpc.os-projects
# role.
openstack_projects:
  - "{{ openstack_demo_project }}"

# Definition of the openstack demo project. Format is as required by the
# stackhpc.os-projects role.
openstack_demo_project:
  name: demo
  description: OpenStack demo project
  project_domain: default
  user_domain: default
  users: "{{ openstack_demo_users }}"
  quotas: "{{ openstack_unlimited_quotas }}"

# List of users in the openstack ResOps team. Format is as required by the
# stackhpc.os-projects role.
openstack_demo_users:
  - name: donald
    roles: "{{ openstack_user_roles }}"
    password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35356433623333336136383036333266336133303238333930383763363638633633636362636363
          6536303264343566646530356131303565323532346434370a613161383464656565396563356438
          34393333633330623366306133366437313630653637353464376562643035353938616632316333
          6134653234383034360a313635633831663930653537386536373533646137653734356530646639
          36393937653838616238646230363534363536313138373731393561636430383661646362616633
          3430626166623232323466326634366338643463303434636632
    email: donald@example.com
openstack_demo_users_examples:
  - name: alice
    password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      <snip>
    email: alice@example.com
    roles: "{{ openstack_admin_roles }}"
  - name: bob
    password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      <snip>
    email: bob@example.com
    roles: "{{ openstack_user_roles }}"

# List of roles to apply to admin users in the openstack demo project.
openstack_admin_roles:
  - admin
  - heat_stack_owner
  # This allows a user admin access to octavia APIs.
  # https://docs.openstack.org/octavia/latest/configuration/policy.html
  - load-balancer_admin

# List of roles to apply to regular users in the openstack demo project.
openstack_user_roles:
  - member
  - heat_stack_owner
  # This allows a user read and write access to octavia APIs.
  # https://docs.openstack.org/octavia/latest/configuration/policy.html
  - load-balancer_member
  # This allows a user read access to Barbican secrets.
  # https://docs.openstack.org/barbican/latest/admin/access_control.html
  - observer

# Dict of quotas to set for projects with unlimited resource quotas
openstack_unlimited_quotas:
  backup_gigabytes: -1
  backups: -1
  cores: -1
  floatingip: -1
  gigabytes: -1
  injected_file_size: -1
  injected_files: -1
  instances: -1
  key_pairs: -1
  per_volume_gigabytes: -1
  ram: -1
  security_group: -1
  security_group_rule: -1
  snapshots: -1
  volumes: -1

###############################################################################
# Configuration of networks, subnets and routers.

# List of networks in the openstack system. Format is as required by the
# stackhpc.os-networks role.
#openstack_networks:

# List of routers in the openstack project. Format is as required by the
# stackhpc.os-networks role.
#openstack_routers:

# List of security groups in the openstack project.
# Format is as required by the stackhpc.os-networks role.
#openstack_security_groups:

# List of RBAC definitions in the openstack projct. Format is as required by the
# stackhpc.os-networks role.
#openstack_networks_rbac:

###############################################################################
# Configuration of nova flavors.

# List of nova flavors in the openstack project. Format is as required by the
# stackhpc.os-flavors role.
#openstack_flavors:

###############################################################################
# Configuration of nova host aggregates.

# List of nova host aggregates. Format is as required by the
# stackhpc.os_host_aggregates role.
#openstack_host_aggregates:

###############################################################################
# Configuration of Glance software images.

# List of Glance images. Format is as required by the stackhpc.os-images role.
#openstack_images:

# List of Diskimage Builder (DIB) elements paths to include in image builds.
#openstack_image_elements:

# List of Diskimage Builder (DIB) elements Git repositories to use in image
# builds.
#openstack_image_git_elements:

###############################################################################
# Configuration of Magnum container clusters.

# List of magnum cluster templates. Format is as required by the
# stackhpc.os-container-clusters role.
#openstack_container_clusters_templates:

###############################################################################
# Configuration variables for generating new Magnum cluster template config.

# These variables must be defined before using the generating new cluster
# templates - see repo README for more details.

# Must have at least 2 CPUs, 4GB RAM and 20GB disk
# magnum_default_master_flavor_name:
# magnum_default_worker_flavor_name:

# Network to create tenant cluster FIPs on
# magnum_external_net_name:

# Provider for cluster loadbalancers (e.g. 'ovn')
# magnum_loadbalancer_provider:

# Kubernetes CNI to use for cluster templates (defaults to 'calico')
# Must be one of the options supported by capi-helm-charts, see
# https://github.com/stackhpc/capi-helm-charts/tree/main/charts/cluster-addons#container-network-interface-cni-plugins
# magnum_default_network_driver:

# Whether to create a master nodes loadbalancer for cluster templates (defaults to 'True')
# magnum_master_lb_enabled:

# Whether to add a floating IP to the loadbalancer for cluster templates (defaults to 'True')
# magnum_cluster_floating_ip_enabled:

# List of nameservers to use for cluster templates
# magnum_cluster_default_dns_nameservers:

# Whether generated cluster templates should be public by default (defaults to 'True')
# magnum_cluster_templates_public:

###############################################################################
# Configuration variables for a CloudKitty ratings service deployment.

#     #    ###   #######  #####    IN ORDER TO SUCCESSFULLY DEPLOY CLOUDKITTY
# #   #   #   #     #     #        'cloudkitty.conf' & 'metrics.yml' MUST BE    
#  #  #   #   #     #     ###      PROVIDED ALONGSIDE THE FOLLOWING CONFIG.
#   # #   #   #     #     #        MORE INFO CAN BE FOUND IN THE README.md
#     #    ###      #     #####    'stackhpc-kayobe-config' DOCS.


# A list where each item is a dictionary mapping the associated fields, 
# with the 'mappings' field also being a list of dictionaries. Example
# of the mappings and their fields can be found below, however for more
# information please refer to the stackhpc.openstack.os_ratings role docs.
#
#openstack_ratings_hashmap_field_mappings:
#  - service: SERVICE_NAME
#    name: FIELD_NAME 
#    mappings:          
#      - value: MAPPING_VALUE
#        cost: MAPPING_COST
#        type: MAPPING_TYPE
#        group: MAPPING_GROUP <---THIS IS OPTIONAL---

# Much like the field mappings above, the service mappings are a list of
# dictionaries, however these are not associated with a field.
#
#openstack_ratings_hashmap_service_mappings:
#  - service: SERVICE_NAME
#    cost: MAPPING_COST
#    type: MAPPING_TYPE
#    group: MAPPING_GROUP <---THIS IS OPTIONAL---

###############################################################################
# Dummy variable to allow Ansible to accept this file.
workaround_ansible_issue_8743: yes
